Added the capability to look in a dyn file for scale factors.

diff --git a/scripts/log_extract b/scripts/log_extract
--- a/scripts/log_extract
+++ b/scripts/log_extract
@@ -30,6 +30,7 @@ if [[ -t 2 ]]; then
     ec='\e[31m' # error color (red)
     wc='\e[33m' # warning color (yellow)
     sc='\e[32m' # success color (green)
+    fc='\e[35m' # file color (magenta)
     nc='\e[39m' # normal color
 fi
 
@@ -54,6 +55,8 @@ Defaults are shown in parentheses.
   -b	center of density galacto-centric distance
   -c	center of mass position, X-Y projection (default)
   -d	center of mass galacto-centric distance
+  -D DF look in the associated dyn file, DF, for scale factors
+  -f	overwrite existing files silently ($force)
   -h	display this help message and exit
   -m	mass (in stars) bound to the cluster
   -n	number of stars bound to the cluster
@@ -69,14 +72,16 @@ Defaults are shown in parentheses.
 
 to_clobber() {
     [[ -e "$1" ]] || return 0
-    if $force; then warn "$1 exists - overwriting..."; return 0
+    if $force; then warn "$fc$1$nc exists - overwriting..."; return 0
     else
-        read -n 1 -p "$1 exists - overwrite? " < /dev/tty
+        read -n1 -p"$(builtin echo -n $fc$1$nc exists - overwrite\?) " </dev/tty
         if [[ "$REPLY" != [Yy] ]]; then
-            [[ "$REPLY" ]] && builtin echo \\bNo. >&2 || builtin echo No. >&2
+            if [[ "$REPLY" ]]; then builtin echo "\b${wc}No$nc" >&2
+	    else builtin echo "${wc}No$nc" >&2
+	    fi
             return 1
         fi
-        builtin echo \\bYes! >&2
+        builtin echo "\b${ec}Yes$nc" >&2
         return 0
     fi
 }
@@ -84,12 +89,14 @@ to_clobber() {
 
 shopt -s expand_aliases nullglob xpg_echo
 
-while getopts :abcdhmno:qS:V option; do
+while getopts :abcdD:fhmno:qS:V option; do
     case $option in
 	a) action=cod_position;;
 	b) action=cod_distance;;
 	c) action=com_position;;
 	d) action=com_distance;;
+	D) dyn="$OPTARG";;
+	f) force=true;;
 	h) usage 0;;
 	m) action=mass;;
 	n) action=star_number;;
@@ -97,7 +104,7 @@ while getopts :abcdhmno:qS:V option; do
 	q) quiet=true;;
 	S) sf=($OPTARG);;
 	V) echo $'\
-log_extract version 0.4, Copyright © 2005  Ernest N. Mamikonyan.
+log_extract version 0.5, Copyright © 2005  Ernest N. Mamikonyan.
 log_extract comes with ABSOLUTELY NO WARRANTY.
 This is free software, and you are welcome to redistribute it
 under certain conditions; see the source for details.
@@ -111,17 +118,28 @@ done
 
 shift $((OPTIND-1))
 
+
 $quiet && echo() { :; } || echo() { builtin echo "$@" >&2; }
 
 
+# scale factors in this order: mass, distance, time
+# e.g., mass: ${sf[0]}, distance: ${sf[1]}, time: ${sf[2]}
 if [[ "$sf" ]]; then
     echo "\
 accepted the following scale factors,
 mass: ${sf[0]}, distance: ${sf[1]}, time: ${sf[2]}"
+elif [[ "$dyn" ]]; then
+    echo -n "searching for scale factors in $fc$dyn$nc..."
+    sf=($(awk '
+BEGIN {
+  while (i < 3 && getline) {
+    if (/^[[:blank:]]*mass_scale[[:blank:]]*=/) { ++i; print 1/$3 }
+    else if (/^[[:blank:]]*size_scale[[:blank:]]*=/) { ++i; print 2.255e-8/$3 }
+    else if (/^[[:blank:]]*time_scale[[:blank:]]*=/) { ++i; print 1/$3 }
+  }
+}' "$dyn"))
 else
-    echo -n searching for scale factors...
-# scale factors in this order: mass, distance, time
-# e.g., mass: ${sf[0]}, distance: ${sf[1]}, time: ${sf[2]}
+    echo -n "searching for scale factors in input..."
     sf=($(awk '
 BEGIN {
   while (i < 3 && getline) {
@@ -130,16 +148,19 @@ BEGIN {
     else if (/^[[:blank:]]*\[T\]:/) { ++i; print $2 }
   }
 }' "$@"))
-    if [[ "$sf" ]]; then
-	echo "${sc}done$nc\nmass: ${sf[0]}, distance: ${sf[1]}, time: ${sf[2]}"
-    else
-	echo "${ec}failed$nc"
-	warn "can't find scale factors in input"
-	sf=(1 1 1)
-    fi
 fi
 
+if [[ "$sf" ]]; then
+    echo "${sc}done$nc\nmass: ${sf[0]}, distance: ${sf[1]}, time: ${sf[2]}"
+else
+    echo "${ec}failed$nc"
+    warn "can't find scale factors - continuing"
+    sf=(1 1 1)
+fi
+
+
 [[ "$output" == /dev/stdout ]] || to_clobber "$output" || exit
+
 
 case $action in
     cod_distance)
