Fixed a bug related to overwritting existing files and added the ability to specify scale factors on the command line.

diff --git a/scripts/log_extract b/scripts/log_extract
--- a/scripts/log_extract
+++ b/scripts/log_extract
@@ -47,7 +47,7 @@ warn() { echo "${0##*/}: $wc$@$nc" >&2; }
 usage() {
     echo "\
 Usage: ${0##*/} [OPTIONS] [LOG FILE] ...
-Extracts various data from Starlab log files.
+Extracts various data from Starlab log files, which may be compressed.
 Defaults are shown in parentheses.
 
   -c	center of mass position, X-Y projection (default)
@@ -57,6 +57,8 @@ Defaults are shown in parentheses.
   -n	number of stars bound to the cluster
   -o F	output to file F ($output)
   -q	suppress all diagnostic output
+  -S SF assume the scale factors SF given in the order: mass, distance, time
+	i.e., -S '91902.6 0.039 0.000377257' (search input)
   -V	display version information and exit
 " >&2
     exit $1
@@ -80,7 +82,7 @@ to_clobber() {
 
 shopt -s expand_aliases nullglob xpg_echo
 
-while getopts :cdhmnoqV option; do
+while getopts :cdhmno:qS:V option; do
     case $option in
 	c) action=com_position;;
 	d) action=com_distance;;
@@ -89,8 +91,9 @@ while getopts :cdhmnoqV option; do
 	n) action=star_number;;
 	o) output="$OPTARG";;
 	q) quiet=true;;
+	S) sf=($OPTARG);;
 	V) echo $'\
-log_extract version 0.1, Copyright © 2005  Ernest N. Mamikonyan.
+log_extract version 0.2, Copyright © 2005  Ernest N. Mamikonyan.
 log_extract comes with ABSOLUTELY NO WARRANTY.
 This is free software, and you are welcome to redistribute it
 under certain conditions; see the source for details.
@@ -107,10 +110,15 @@ shift $((OPTIND-1))
 $quiet && echo() { :; } || echo() { builtin echo "$@" >&2; }
 
 
-echo -n searching for scale factors...
+if [[ "$sf" ]]; then
+    echo "\
+accepted the following scale factors,
+mass: ${sf[0]}, distance: ${sf[1]}, time: ${sf[2]}"
+else
+    echo -n searching for scale factors...
 # scale factors in this order: mass, distance, time
 # e.g., mass: ${sf[0]}, distance: ${sf[1]}, time: ${sf[2]}
-sf=($(awk '
+    sf=($(awk '
 BEGIN {
   while (i < 3 && getline) {
     if (/^[[:blank:]]*\[m\]:/) { ++i; print $2 }
@@ -118,37 +126,47 @@ BEGIN {
     else if (/^[[:blank:]]*\[T\]:/) { ++i; print $2 }
   }
 }' "$@"))
-
-if [[ "$sf" ]]; then
-    echo "${sc}done$nc\nmass: ${sf[0]}, distance: ${sf[1]}, time: ${sf[2]}"
-else
-    echo "${ec}failed$nc"
-    error "can't find scale factors in input" 2
+    if [[ "$sf" ]]; then
+	echo "${sc}done$nc\nmass: ${sf[0]}, distance: ${sf[1]}, time: ${sf[2]}"
+    else
+	echo "${ec}failed$nc"
+	error "can't find scale factors in input" 2
+    fi
 fi
+
+[[ "$output" == /dev/stdout ]] || to_clobber "$output" || exit
 
 case $action in
     com_distance)
+	echo -n computing the galacto-centric distance as a function of time...
 	awk "
 /center of mass position = / {
   print ${sf[2]}*i++, sqrt(\$6^2+\$7^2+\$8^2)*${sf[1]}
 }" "$@" > "$output"
+	echo done
 	;;
     com_position)
+	echo -n computing the center of mass position in the X-Y plane...
 	awk "
 /center of mass position = / {
   print \$6*${sf[1]}, \$7*${sf[1]}
 }" "$@" > "$output"
+	echo done
 	;;
     mass)
+	echo -n computing the mass of the cluster as a function of time...
 	awk "
 /^Time = / {
   print \$3*${sf[2]}, substr(\$12,2)*${sf[0]}
 }" "$@" > "$output"
+	echo done
 	;;
     star_number)
+	echo -n computing the number of bound stars as a function of time...
 	awk "
 /^Time = / {
   print \$3*${sf[2]}, substr(\$7,2)
 }" "$@" > "$output"
-
+	echo done
+	;;
 esac
